# Generated by Django 5.2.7 on 2025-10-18 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_asistencia.docente'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='materia',
            field=models.CharField(choices=[('Matemáticas', 'Matemáticas'), ('Lengua', 'Lengua'), ('Ciencias', 'Ciencias'), ('Historia', 'Historia'), ('Inglés', 'Inglés')], max_length=100),
        ),
    ]
