# Generated by Django 5.2.8 on 2025-11-22 01:05

from django.db import migrations
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('control_asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='user',
            field=models.OneToOneField(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True),
        ),

    ]
