# Generated by Django 5.2.8 on 2025-11-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_asistencia', '0002_auto_20251121_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
