# Generated by Django 5.2.8 on 2025-11-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_asistencia', '0003_docente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='documento',
            field=models.CharField(default='0000', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
