# Generated by Django 5.2.8 on 2026-08-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_asistencia', '0002_alter_asistencia_docente_alter_docente_materia'),
        ('control_asistencia', '0004_alter_docente_documento'),
    ]

    operations = [
    ]
